# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 00:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0014_auto_20170820_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name=b'email address')),
                ('company_email', models.EmailField(blank=True, max_length=255, null=True, unique=True, verbose_name=b'company email')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('role', models.CharField(blank=True, default=b'', max_length=200, null=True)),
                ('start_date', models.DateField(default=datetime.datetime.now)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=datetime.datetime.now)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.Company')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', users.models.AccountManager()),
            ],
        ),
    ]
