# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-02 00:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20170529_2016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='industry',
        ),
        migrations.DeleteModel(
            name='Industry',
        ),
    ]
