# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-02 02:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20170602_0226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='postal_code',
        ),
    ]
