# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-08 00:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='board',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='jobs.Board'),
        ),
    ]
