# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 01:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0014_auto_20170820_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_position', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('Company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.Company')),
            ],
        ),
        migrations.RemoveField(
            model_name='board',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='created_on',
        ),
        migrations.AddField(
            model_name='comment_user',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.Comment'),
        ),
    ]
