# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 17:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0017_auto_20170902_1716'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Company',
            new_name='company',
        ),
    ]
