# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0020_auto_20170902_2013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='wish',
        ),
        migrations.AddField(
            model_name='board',
            name='slug',
            field=models.SlugField(default='NY-tech', max_length=100, unique=True, verbose_name='slug'),
            preserve_default=False,
        ),
    ]
