# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0021_auto_20170902_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
