# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0024_auto_20170908_0312'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedjobs',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
