# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-07 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0027_board_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='logo',
            field=models.ImageField(blank=True, default='images/publishers/no-image.png', upload_to='images/publishers'),
        ),
    ]
