# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-06 22:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_auto_20171106_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='purpose',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='landing.Purpose'),
        ),
    ]
