# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-07 19:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_auto_20180107_0006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='site',
            new_name='name',
        ),
    ]
